"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Guru Shreyas Potta and Ray Arcand, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.



UT EID 1: gp23568
UT EID 2: ra42693
"""


def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    hold = [""]

    for i in range(n):
        temp = s[i]
        for j in range(i+1, n):
            temp += s[j]
            hold.append(temp)
        if n == 1:
            hold.append(temp)
    m = len(hold)
    for k in range(m):
        word = hold[k]
        for l in range(len(word)):
            if word.count(s[l]) > 1:
                hold[k] = 0
        if hold[k] != 0:
            hold[k] = len(hold[k])
    return max(hold)


def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """

    n = len(s)
    longest = 0
    duplicate_bool = False
    for i in range(n):
        tracker = [0] * 256
        duplicate_bool = False
        for j in range(i, n):
            if tracker[ord(s[j])] != 1:
                tracker[ord(s[j])] = 1
            else:
                tracker[ord(s[j])] += 1
                duplicate_bool = True
            if not duplicate_bool:
                longest = max(longest, j-i+1)
    return longest


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    longest = 0
    for i in range(n):
        tracker = [0] * 256
        for j in range(i, n):
            if tracker[ord(s[j])] != 1:
                tracker[ord(s[j])] = 1
            else:
                break
            longest = max(longest, j - i + 1)
    return longest
